name: Run E2E Tests
on:
 workflow_dispatch
 
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3  # Checkout your repository code
     - name: Create environment file
       run: |
         echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
         echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
       env:
         SECRETS: ${{ secrets }}
     - name: Install dependencies (if using dotenv)
       run: npm install dotenv --only=dev  # Install dotenv as a development dependency
       if: env.USE_DOTENV  # Only install if USE_DOTENV is set to true in secrets
     - name: Run tests
       run: npm install && npm test
