name: Run E2E Tests
on:
 workflow_dispatch:

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3  # Checkout your repository code
     - name: Create environment file
       run: |
         echo "BASE_URL=${{ secrets.API_URL }}" >> .env
         echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
       env:
         SECRETS: ${{ secrets }}
     - name: Run tests
       run: npm install && npm test
