name: quatt_test_api

on:
 workflow_dispatch:
 push:
   branches: [main]
 pull_request:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    steps:     
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      uses: ozaytsev86/create-env-file@v1
      with:
          API_URL: ${{ secrets.API_URL }}
          BEARER_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - run: npm install
    - run: npm test
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
